
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/theme.min.css
- https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css

# scripts loaded in the end of the body
scripts:
